/**
 * Cache validation: may this previously generated package be served?
 *
 * Phase 6A checked only the package format string and the source fingerprint,
 * so a package that was truncated, generated by an older engine, or stripped
 * of its IR could still be reported as "source unchanged" and served. This
 * validator inspects the package for real, and its verdict is structured so
 * callers can distinguish "rebuild it" from "refresh regenerable metadata".
 */
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import {
  IMPORT_REPORT_FORMAT,
  IMPORT_REPORT_VERSION,
  isCompatibleEngineVersion,
  isSupportedIrSchema,
  isSupportedManifestSchema,
  isSupportedPackageFormat,
  isSupportedPackageSchema,
  isSupportedProfileVersion,
  type AssetManifest,
  type GamePackageMeta,
  type ImportReport,
  type IrScene,
  type PlayerBranding,
} from "kid-contracts";

export interface CacheValidation {
  /** True only when the package may be served as-is. */
  valid: boolean;
  /** Human-readable reasons, most important first; empty when valid. */
  reasons: string[];
  /**
   * The converted content is intact and only regenerable metadata is stale
   * (currently: product branding drift). Such a package is refreshed in
   * place rather than reconverted.
   */
  canMigrate: boolean;
  /** The package must be discarded and rebuilt from the source. */
  mustRebuild: boolean;
  /** Parsed metadata, when game.json was readable. */
  meta?: GamePackageMeta;
  /** Parsed import report, when it was readable. */
  report?: ImportReport;
}

export interface CacheExpectation {
  packageDir: string;
  /** Fingerprint the source installation currently hashes to. */
  fingerprint: string;
  /** Algorithm that produced the fingerprint; a different one is not
   * comparable, so the package must be rebuilt. */
  fingerprintAlgo: string;
  gameId: string;
  /** Scene a New Game starts at; its IR must be present and executable. */
  startScene: string;
  /** Branding the product currently wants (drift is migratable, not fatal). */
  branding?: PlayerBranding;
}

/** Structural check of one decompiled scene: enough to know the runtime can
 * execute it, without walking every op. */
export function validateSceneIr(scene: unknown, name: string): string | null {
  if (typeof scene !== "object" || scene === null) return `${name}: not an object`;
  const s = scene as Partial<IrScene>;
  if (!isSupportedIrSchema(s.formatVersion)) {
    return `${name}: unsupported IR schema ${String(s.formatVersion)}`;
  }
  if (typeof s.scene !== "string" || s.scene.length === 0) return `${name}: no scene name`;
  if (typeof s.entry !== "string" || s.entry.length === 0) return `${name}: no entry block`;
  if (typeof s.blocks !== "object" || s.blocks === null) return `${name}: no blocks`;
  const blocks = s.blocks as Record<string, unknown>;
  if (Object.keys(blocks).length === 0) return `${name}: no blocks`;
  const entry = blocks[s.entry];
  if (entry === undefined) return `${name}: entry block "${s.entry}" is missing`;
  if (!Array.isArray((entry as { ops?: unknown }).ops)) return `${name}: entry block has no ops`;
  return null;
}

const rebuild = (reasons: string[], extra: Partial<CacheValidation> = {}): CacheValidation => ({
  valid: false,
  reasons,
  canMigrate: false,
  mustRebuild: true,
  ...extra,
});

function readJson<T>(path: string): { ok: true; value: T } | { ok: false; error: string } {
  try {
    return { ok: true, value: JSON.parse(readFileSync(path, "utf8")) as T };
  } catch (err) {
    return { ok: false, error: (err as Error).message };
  }
}

/** Whether two branding blocks would render the same shell. */
function brandingEqual(a: PlayerBranding | undefined, b: PlayerBranding | undefined): boolean {
  return JSON.stringify(a ?? null) === JSON.stringify(b ?? null);
}

/**
 * Validate a cached package against the current source and engine. Reads only
 * metadata plus directory listings: never rewrites or deletes anything, so a
 * failed validation cannot damage a package the caller may still want.
 */
export function validateCachedPackage(expect: CacheExpectation): CacheValidation {
  const { packageDir } = expect;
  if (!existsSync(packageDir) || !statSync(packageDir).isDirectory()) {
    return rebuild([`no cached package at ${packageDir}`]);
  }

  // ---- game.json ---------------------------------------------------------
  const gameJsonPath = join(packageDir, "game.json");
  if (!existsSync(gameJsonPath)) return rebuild(["game.json is missing (import never completed)"]);
  const metaRead = readJson<GamePackageMeta>(gameJsonPath);
  if (!metaRead.ok) return rebuild([`game.json is corrupt: ${metaRead.error}`]);
  const meta = metaRead.value;

  const reasons: string[] = [];
  if (!isSupportedPackageFormat(meta.format)) {
    reasons.push(`not a game package (format "${String(meta.format)}")`);
  }
  if (!isSupportedPackageSchema(meta.schemaVersion)) {
    reasons.push(`unsupported package schemaVersion ${String(meta.schemaVersion)}`);
  }
  if (!isCompatibleEngineVersion(meta.engineVersion)) {
    reasons.push(`built by an incompatible engine (${String(meta.engineVersion)})`);
  }
  if (meta.gameId !== expect.gameId) {
    reasons.push(`package is for gameId "${String(meta.gameId)}", not "${expect.gameId}"`);
  }
  if (meta.sourceFingerprint !== expect.fingerprint) {
    reasons.push(`source changed (package ${String(meta.sourceFingerprint)}, now ${expect.fingerprint})`);
  }
  if (!isSupportedProfileVersion(meta.profile?.profileVersion)) {
    reasons.push(`unsupported game profile version ${String(meta.profile?.profileVersion)}`);
  }
  if (reasons.length > 0) return rebuild(reasons, { meta });

  // ---- import report: proof the import ran to completion ------------------
  const reportPath = join(packageDir, "import-report.json");
  if (!existsSync(reportPath)) {
    return rebuild(["import-report.json is missing (package predates completion tracking)"], { meta });
  }
  const reportRead = readJson<ImportReport>(reportPath);
  if (!reportRead.ok) return rebuild([`import-report.json is corrupt: ${reportRead.error}`], { meta });
  const report = reportRead.value;
  if (report.format !== IMPORT_REPORT_FORMAT) {
    return rebuild([`import-report.json has format "${String(report.format)}"`], { meta });
  }
  if (report.version !== IMPORT_REPORT_VERSION) {
    return rebuild([`unsupported import-report version ${String(report.version)}`], { meta });
  }
  if (report.status !== "complete") {
    return rebuild([`the recorded import did not complete (status "${String(report.status)}")`], { meta, report });
  }
  if (report.gameId !== expect.gameId) {
    return rebuild([`import-report.json is for gameId "${String(report.gameId)}"`], { meta, report });
  }
  if (report.sourceFingerprint !== expect.fingerprint) {
    return rebuild(["import-report.json describes a different source"], { meta, report });
  }
  const versions = report.schemaVersions;
  if (typeof versions !== "object" || versions === null) {
    return rebuild(["import-report.json records no schema versions"], { meta, report });
  }
  if (versions.fingerprintAlgo !== expect.fingerprintAlgo) {
    return rebuild(
      [`built with fingerprint algorithm "${String(versions.fingerprintAlgo)}", now "${expect.fingerprintAlgo}"`],
      { meta, report },
    );
  }
  if (!isSupportedPackageSchema(versions.package)) {
    return rebuild([`import recorded unsupported package schema ${String(versions.package)}`], { meta, report });
  }
  if (!isSupportedManifestSchema(versions.manifest)) {
    return rebuild([`import recorded unsupported manifest schema ${String(versions.manifest)}`], { meta, report });
  }
  if (!isSupportedIrSchema(versions.ir)) {
    return rebuild([`import recorded unsupported IR schema ${String(versions.ir)}`], { meta, report });
  }
  if (!isSupportedProfileVersion(versions.profile)) {
    return rebuild([`import recorded unsupported profile version ${String(versions.profile)}`], { meta, report });
  }
  if (!isCompatibleEngineVersion(versions.engine)) {
    return rebuild([`import was produced by an incompatible engine (${String(versions.engine)})`], { meta, report });
  }
  if (!Array.isArray(report.scripts?.scenes) || report.scripts.scenes.length !== report.scripts.decompiled) {
    return rebuild(
      [`import-report.json lists ${report.scripts?.scenes?.length ?? 0} scenes but recorded ` +
        `${String(report.scripts?.decompiled)} decompiled`],
      { meta, report },
    );
  }
  if (report.scripts.failed !== 0) {
    return rebuild([`the import recorded ${report.scripts.failed} failed script(s)`], { meta, report });
  }

  // ---- manifest ----------------------------------------------------------
  const assetsDir = join(packageDir, meta.paths?.assets ?? "assets");
  const manifestPath = join(assetsDir, "manifest.json");
  if (!existsSync(manifestPath)) return rebuild(["assets/manifest.json is missing"], { meta, report });
  const manifestRead = readJson<AssetManifest>(manifestPath);
  if (!manifestRead.ok) return rebuild([`assets/manifest.json is corrupt: ${manifestRead.error}`], { meta, report });
  const manifest = manifestRead.value;
  if (!isSupportedManifestSchema(manifest.formatVersion)) {
    return rebuild([`unsupported manifest schema ${String(manifest.formatVersion)}`], { meta, report });
  }
  if (!manifest.assets || typeof manifest.assets !== "object") {
    return rebuild(["assets/manifest.json has no asset table"], { meta, report });
  }
  if (Object.keys(manifest.assets).length !== report.assets.indexed) {
    return rebuild(
      [`manifest holds ${Object.keys(manifest.assets).length} assets, the import recorded ${report.assets.indexed}`],
      { meta, report },
    );
  }

  // ---- IR ----------------------------------------------------------------
  const irDir = join(packageDir, meta.paths?.ir ?? "ir");
  if (!existsSync(irDir) || !statSync(irDir).isDirectory()) {
    return rebuild(["the IR directory is missing"], { meta, report });
  }
  const present = new Set(
    readdirSync(irDir)
      .filter((f) => f.endsWith(".json"))
      .map((f) => f.slice(0, -".json".length).toLowerCase()),
  );
  const startScene = expect.startScene.toLowerCase();
  if (!present.has(startScene)) {
    return rebuild([`the start scene "${expect.startScene}" has no IR`], { meta, report });
  }
  // Parse the start scene for real: a package whose report looks complete but
  // whose IR is malformed or from another schema must never be served, and
  // this is the one scene every New Game needs.
  const startRead = readJson<unknown>(join(irDir, `${startScene}.json`));
  if (!startRead.ok) {
    return rebuild([`the start scene IR is corrupt: ${startRead.error}`], { meta, report });
  }
  const startProblem = validateSceneIr(startRead.value, `${startScene}.json`);
  if (startProblem) return rebuild([`the start scene IR is unusable - ${startProblem}`], { meta, report });
  const expectedScenes = report.scripts.scenes.map((s) => s.toLowerCase());
  const absent = expectedScenes.filter((s) => !present.has(s));
  if (absent.length > 0) {
    return rebuild(
      [
        `${absent.length} of ${expectedScenes.length} scene files are missing ` +
          `(e.g. ${absent.slice(0, 3).join(", ")})`,
      ],
      { meta, report },
    );
  }
  if (meta.startScene.toLowerCase() !== startScene) {
    return rebuild(
      [`package starts at "${meta.startScene}", the product expects "${expect.startScene}"`],
      { meta, report },
    );
  }

  // ---- movies (structure only; absent movies are a documented warning) ----
  const movieDir = meta.paths?.movies ? join(packageDir, meta.paths.movies) : null;
  if (movieDir && existsSync(movieDir) && !statSync(movieDir).isDirectory()) {
    return rebuild(["the movies path is not a directory"], { meta, report });
  }

  // ---- regenerable metadata ---------------------------------------------
  if (expect.branding && !brandingEqual(meta.branding, expect.branding)) {
    return {
      valid: false,
      reasons: ["product branding changed since the package was generated"],
      canMigrate: true,
      mustRebuild: false,
      meta,
      report,
    };
  }

  return { valid: true, reasons: [], canMigrate: false, mustRebuild: false, meta, report };
}
